export const EVENT_LIMITS = {
  MAX_EVENT_TYPE_LENGTH: 128,
  MAX_USER_ID_LENGTH: 128,
  MAX_SESSION_ID_LENGTH: 128,
  MAX_METADATA_KEYS: 100,
  MAX_METADATA_KEY_LENGTH: 64,
  MAX_METADATA_VALUE_LENGTH: 1024,
} as const;
